import type {
  DashboardSnapshot,
  EndgameLesson,
  OpeningVariation,
  ReviewItem,
} from "@/types/lotus";

export const dashboardSnapshot: DashboardSnapshot = {
  goalMinutes: 20,
  studiedMinutes: 12,
  streakDays: 18,
  openingsMastered: 24,
  endgamesMastered: 15,
  lessonsCompleted: 312,
  accuracy: 92,
  xp: 18450,
  legendProgress: 78,
  currentRank: "Master",
};

export const featuredOpening: OpeningVariation = {
  id: "italian-giuoco-piano-center",
  opening: "Italian Game",
  variation: "Giuoco Piano Center",
  category: "White",
  side: "white",
  eco: "C50",
  difficulty: 2,
  overview:
    "A direct Italian setup that develops quickly, contests the center, and keeps kingside pressure available.",
  keyIdeas: [
    "Develop the king knight before committing the center.",
    "Aim the bishop at f7 while keeping c3 and d4 available.",
    "Use the central break only after Black has committed the knight.",
  ],
  movesSan: ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d4"],
  pgn: "1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d4",
  concepts: ["Development", "Central break", "King safety"],
  commonMistakes: [
    "Playing d4 before c3 gives Black easy central trades.",
    "Moving the same piece repeatedly lets Black equalize development.",
  ],
  tacticalMotifs: ["f7 pressure", "central pins", "discovered attacks"],
  modelGames: ["Greco - NN, 1620", "Anand - Kramnik, 2008"],
};

export const openingCatalog: OpeningVariation[] = [
  featuredOpening,
  {
    id: "london-main-system",
    opening: "London System",
    variation: "Main Setup",
    category: "White",
    side: "white",
    eco: "D02",
    difficulty: 1,
    overview:
      "A reliable queen pawn system built around Bf4, e3, Nf3, and a compact center.",
    keyIdeas: ["Build a stable pawn chain.", "Keep piece placement flexible."],
    movesSan: ["d4", "Nf6", "Nf3", "d5", "Bf4", "e6", "e3"],
    pgn: "1. d4 Nf6 2. Nf3 d5 3. Bf4 e6 4. e3",
    concepts: ["Piece coordination", "Quiet pressure"],
    commonMistakes: ["Locking the dark-squared bishop inside the pawn chain."],
    tacticalMotifs: ["Bxh7 sacrifices", "Ne5 outposts"],
    modelGames: ["Kamsky - Shankland, 2014"],
  },
  {
    id: "sicilian-najdorf-shell",
    opening: "Sicilian Defense",
    variation: "Najdorf Structure",
    category: "Black vs e4",
    side: "black",
    eco: "B90",
    difficulty: 4,
    overview:
      "A dynamic Sicilian structure where Black controls key central squares and prepares queenside expansion.",
    keyIdeas: ["Challenge d4.", "Prepare ...a6 and ...e5 or ...e6."],
    movesSan: ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"],
    pgn: "1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6",
    concepts: ["Imbalance", "Counterplay", "Pawn breaks"],
    commonMistakes: ["Playing queenside moves while the king remains exposed."],
    tacticalMotifs: ["exchange sacrifice on c3", "dark-square pressure"],
    modelGames: ["Kasparov - Topalov, 1999"],
  },
  {
    id: "kings-indian-classical",
    opening: "King's Indian Defense",
    variation: "Classical",
    category: "Black vs d4",
    side: "black",
    eco: "E97",
    difficulty: 4,
    overview:
      "A counterattacking setup where Black invites a broad center and then undermines it with pawn breaks.",
    keyIdeas: ["Castle quickly.", "Break with ...e5 or ...c5.", "Build kingside activity."],
    movesSan: ["d4", "Nf6", "c4", "g6", "Nc3", "Bg7", "e4", "d6", "Nf3", "O-O"],
    pgn: "1. d4 Nf6 2. c4 g6 3. Nc3 Bg7 4. e4 d6 5. Nf3 O-O",
    concepts: ["Counterattack", "Pawn storms", "Space concession"],
    commonMistakes: ["Opening the center before development is complete."],
    tacticalMotifs: ["Greek gift patterns", "rook lifts", "knight sacrifices"],
    modelGames: ["Fischer - Myagmarsuren, 1967"],
  },
];

export const endgameCatalog: EndgameLesson[] = [
  {
    id: "lucena-bridge",
    name: "Lucena Bridge",
    category: "Rook Endgames",
    fen: "8/8/8/8/2K5/8/1P1R4/1k6 w - - 0 1",
    objective: "Promote the pawn with the rook shield.",
    winningMethod: "Cut off the king, advance the pawn, then build a bridge with the rook.",
    commonErrors: ["Checking too early.", "Letting the defender's king back in front of the pawn."],
    hints: ["Improve the rook first.", "The king needs shelter from side checks."],
    engineEvaluation: "+-",
    difficulty: 4,
    tags: ["rook", "promotion", "bridge"],
  },
  {
    id: "philidor-draw",
    name: "Philidor Defense",
    category: "Rook Endgames",
    fen: "8/8/8/3k4/8/3K4/3P4/3Rr3 b - - 0 1",
    objective: "Hold the draw by keeping the rook active.",
    winningMethod: "Maintain the third-rank defense until the pawn advances.",
    commonErrors: ["Dropping the rook to the back rank too soon."],
    hints: ["Hold the third rank.", "Only check from behind after the pawn advances."],
    engineEvaluation: "=",
    difficulty: 3,
    tags: ["rook", "defense", "draw"],
  },
  {
    id: "king-pawn-opposition",
    name: "Basic Opposition",
    category: "King + Pawn",
    fen: "8/8/8/8/3k4/8/3K4/3P4 w - - 0 1",
    objective: "Win or hold the critical squares with king opposition.",
    winningMethod: "Use waiting moves and direct opposition to gain entry.",
    commonErrors: ["Pushing the pawn before the king has opposition."],
    hints: ["Move the king first.", "Count the key squares before advancing."],
    engineEvaluation: "=",
    difficulty: 1,
    tags: ["opposition", "pawn", "king"],
  },
];

export const reviewQueue: ReviewItem[] = [
  {
    id: "review-italian",
    title: "Italian Game",
    subtitle: "Giuoco Piano Center",
    lessonKind: "opening",
    rank: "Legend",
    confidence: 91,
    dueLabel: "Due now",
  },
  {
    id: "review-lucena",
    title: "Lucena",
    subtitle: "Bridge building",
    lessonKind: "endgame",
    rank: "Expert",
    confidence: 76,
    dueLabel: "Today",
  },
  {
    id: "review-kid",
    title: "King's Indian",
    subtitle: "Classical structure",
    lessonKind: "opening",
    rank: "Advanced",
    confidence: 68,
    dueLabel: "Today",
  },
];
